all:
  vars:
    ansible_user: ubuntu
    ansible_become: yes

  hosts:
    laiterie:
      vxlan_interface_address: 172.16.1.19
      priority: 244
    gallia:
      vxlan_interface_address: 172.16.1.13
      priority: 245
    hautepierre:
      vxlan_interface_address: 172.16.1.15
      priority: 246
