---
- hosts: all
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: keepalived
      tags: keepalived
    - role: docker
      tags: docker
    - role: consul
      tags: consul
    - role: nomad
      tags: nomad
