---
- name: "Add group 'nomad'"
  ansible.builtin.group:
    name: nomad
    state: present

- name: "Add user 'nomad'"
  ansible.builtin.user:
    name: nomad
    group: nomad
    home: /opt/nomad
    create_home: true
    system: true
    shell: /bin/false
    state: present

- name: "Create Nomad configuration directory"
  ansible.builtin.file:
    path: /etc/nomad.d/
    owner: nomad
    group: nomad
    state: directory

- name: "Deploy Nomad systemd service"
  ansible.builtin.template:
    src: nomad.service
    dest: /etc/systemd/system/nomad.service
    become: yes
  notify: Reload systemd

- include_tasks: server.yml

- ansible.builtin.meta: flush_handlers

- name: "Enable and start Nomad"
  ansible.builtin.systemd:
    name: nomad.service
    enabled: true
    state: started

- name: "Restart Nomad"
  ansible.builtin.systemd:
    name: nomad.service
    state: restarted

- name: "Wait for Nomad to start"
  ansible.builtin.wait_for:
    port: 4646
    timeout: 10

- name: "Join Nomad cluster"
  command: nomad server join gare-centrale
  become: true

- name: "Create Nomad job directory"
  ansible.builtin.file:
    path: /etc/nomad.d/jobs/
    owner: nomad
    group: nomad
    state: directory

- name: "Copy job configuration file"
  ansible.builtin.template:
    src: job.hcl
    dest: /etc/nomad.d/jobs/job.hcl
    owner: nomad
    group: nomad
    mode: "0644"

- name: "Submit Nomad job"
  command: nomad run /etc/nomad.d/jobs/job.hcl
  become: true
