---
- name: "Udpate and install keepalived"
  ansible.builtin.apt:
    name: keepalived
    update_cache: yes
    
- name: "Deploy the configuration"
  ansible.builtin.template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: Restart Keepalived

