---
- name: Update repositories cache and install "keepalived" package
  ansible.builtin.apt:
    name: keepalived
    update_cache: yes
    
- name: "Deploy the Keepalived configuration"
  ansible.builtin.template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: Restart Keepalived