---
- name: "Add Nomad to Docker group"
  ansible.builtin.user:
    name: "nomad"
    groups: "docker"
    append: "yes"

- name: "Ensure Docker config directory is present"
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: "Enable and start Docker"
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
